import type { Payload } from 'payload'
import { getGameMediaId, gameImageMap } from './media'

interface GameSeedData {
  slug: string
  title: string
  provider: string
  type: 'slot' | 'table' | 'live' | 'instant'
  tags: { tag: string }[]
  shortDescription: string
  popularityScore: number
  jackpotAmount?: number
  minBet: number
  maxBet: number
  rtp?: number
  volatility?: 'low' | 'medium' | 'high'
  minVipLevel?: 'bronze' | 'silver' | 'gold' | 'platinum'
  badges?: ('new' | 'exclusive' | 'hot' | 'jackpot' | 'featured')[]
  status: 'enabled' | 'disabled'
}

const gamesData: GameSeedData[] = [
  // AUTO-GENERATED GAMES FROM AVAILABLE IMAGES (30 games)
  {
    slug: 'legendary-castle',
    title: 'Legendary Castle',
    provider: 'Push Gaming',
    type: 'live',
    tags: [{ tag: 'classic' }, { tag: 'jackpot' }],
    shortDescription: 'Experience thrilling gameplay with Legendary Castle.',
    popularityScore: 87,
    minBet: 0.2,
    maxBet: 200,
    rtp: 96.25,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'divine-temple',
    title: 'Divine Temple',
    provider: 'Push Gaming',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'multiplier' }],
    shortDescription: 'Experience thrilling gameplay with Divine Temple.',
    popularityScore: 71,
    minBet: 0.2,
    maxBet: 1000,
    rtp: 97.16,
    volatility: 'low',
    minVipLevel: 'platinum',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'magic-fortune',
    title: 'Magic Fortune',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'classic' }, { tag: 'jackpot' }],
    shortDescription: 'Experience thrilling gameplay with Magic Fortune.',
    popularityScore: 96,
    minBet: 1.0,
    maxBet: 500,
    rtp: 94.76,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'ruby-dynasty',
    title: 'Ruby Dynasty',
    provider: 'Red Tiger',
    type: 'live',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Experience thrilling gameplay with Ruby Dynasty.',
    popularityScore: 92,
    minBet: 0.1,
    maxBet: 500,
    rtp: 97.17,
    volatility: 'low',
    minVipLevel: 'platinum',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'blazing-carnival',
    title: 'Blazing Carnival',
    provider: 'Microgaming',
    type: 'slot',
    tags: [{ tag: 'classic' }, { tag: 'multiplier' }],
    shortDescription: 'Experience thrilling gameplay with Blazing Carnival.',
    popularityScore: 95,
    minBet: 0.2,
    maxBet: 100,
    rtp: 97.61,
    volatility: 'high',
    badges: ['exclusive'],
    status: 'enabled',
  },
  {
    slug: 'magic-lion',
    title: 'Magic Lion',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'free-spins' }, { tag: 'classic' }],
    shortDescription: 'Experience thrilling gameplay with Magic Lion.',
    popularityScore: 85,
    minBet: 0.5,
    maxBet: 100,
    rtp: 95.3,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'ruby-olympus',
    title: 'Ruby Olympus',
    provider: 'Microgaming',
    type: 'live',
    tags: [{ tag: 'classic' }, { tag: 'multiplier' }],
    shortDescription: 'Experience thrilling gameplay with Ruby Olympus.',
    popularityScore: 72,
    minBet: 1.0,
    maxBet: 200,
    rtp: 94.57,
    volatility: 'low',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'crystal-vikings',
    title: 'Crystal Vikings',
    provider: 'Red Tiger',
    type: 'table',
    tags: [{ tag: 'bonus' }, { tag: 'free-spins' }],
    shortDescription: 'Experience thrilling gameplay with Crystal Vikings.',
    popularityScore: 89,
    minBet: 1.0,
    maxBet: 1000,
    rtp: 99.33,
    volatility: 'high',
    minVipLevel: 'gold',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'emerald-kingdom',
    title: 'Emerald Kingdom',
    provider: 'Pragmatic Play',
    type: 'live',
    tags: [{ tag: 'classic' }, { tag: 'jackpot' }],
    shortDescription: 'Experience thrilling gameplay with Emerald Kingdom.',
    popularityScore: 89,
    minBet: 0.5,
    maxBet: 500,
    rtp: 97.31,
    volatility: 'high',
    minVipLevel: 'gold',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'ancient-dynasty',
    title: 'Ancient Dynasty',
    provider: 'Evolution',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Experience thrilling gameplay with Ancient Dynasty.',
    popularityScore: 79,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.39,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'ancient-gems',
    title: 'Ancient Gems',
    provider: 'Push Gaming',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'bonus' }],
    shortDescription: 'Experience thrilling gameplay with Ancient Gems.',
    popularityScore: 88,
    minBet: 0.1,
    maxBet: 200,
    rtp: 96.75,
    volatility: 'high',
    minVipLevel: 'gold',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'cosmic-dragons',
    title: 'Cosmic Dragons',
    provider: 'Microgaming',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'classic' }],
    shortDescription: 'Experience thrilling gameplay with Cosmic Dragons.',
    popularityScore: 78,
    minBet: 0.5,
    maxBet: 100,
    rtp: 94.56,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'golden-festival',
    title: 'Golden Festival',
    provider: 'Microgaming',
    type: 'table',
    tags: [{ tag: 'bonus' }, { tag: 'adventure' }],
    shortDescription: 'Experience thrilling gameplay with Golden Festival.',
    popularityScore: 72,
    minBet: 0.2,
    maxBet: 100,
    rtp: 97.45,
    volatility: 'high',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'sacred-dynasty',
    title: 'Sacred Dynasty',
    provider: 'Microgaming',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'adventure' }],
    shortDescription: 'Experience thrilling gameplay with Sacred Dynasty.',
    popularityScore: 99,
    minBet: 0.2,
    maxBet: 200,
    rtp: 97.97,
    volatility: 'high',
    minVipLevel: 'gold',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'silver-dynasty',
    title: 'Silver Dynasty',
    provider: 'Evolution',
    type: 'slot',
    tags: [{ tag: 'classic' }, { tag: 'jackpot' }],
    shortDescription: 'Experience thrilling gameplay with Silver Dynasty.',
    popularityScore: 82,
    minBet: 0.5,
    maxBet: 1000,
    rtp: 97.25,
    volatility: 'low',
    minVipLevel: 'platinum',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'royal-phoenix',
    title: 'Royal Phoenix',
    provider: 'Push Gaming',
    type: 'table',
    tags: [{ tag: 'free-spins' }, { tag: 'multiplier' }],
    shortDescription: 'Experience thrilling gameplay with Royal Phoenix.',
    popularityScore: 84,
    minBet: 0.5,
    maxBet: 200,
    rtp: 98.41,
    volatility: 'low',
    minVipLevel: 'platinum',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'mystic-olympus',
    title: 'Mystic Olympus',
    provider: 'Microgaming',
    type: 'slot',
    tags: [{ tag: 'classic' }, { tag: 'jackpot' }],
    shortDescription: 'Experience thrilling gameplay with Mystic Olympus.',
    popularityScore: 78,
    minBet: 0.2,
    maxBet: 500,
    rtp: 97.23,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'bronze-sphinx',
    title: 'Bronze Sphinx',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'free-spins' }, { tag: 'jackpot' }],
    shortDescription: 'Experience thrilling gameplay with Bronze Sphinx.',
    popularityScore: 70,
    minBet: 0.2,
    maxBet: 1000,
    rtp: 97.05,
    volatility: 'low',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'ancient-stars',
    title: 'Ancient Stars',
    provider: 'Red Tiger',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'bonus' }],
    shortDescription: 'Experience thrilling gameplay with Ancient Stars.',
    popularityScore: 78,
    minBet: 1.0,
    maxBet: 1000,
    rtp: 95.12,
    volatility: 'medium',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'emerald-riches',
    title: 'Emerald Riches',
    provider: 'Push Gaming',
    type: 'table',
    tags: [{ tag: 'jackpot' }, { tag: 'classic' }],
    shortDescription: 'Experience thrilling gameplay with Emerald Riches.',
    popularityScore: 87,
    minBet: 0.2,
    maxBet: 200,
    rtp: 97.55,
    volatility: 'medium',
    badges: ['exclusive'],
    status: 'enabled',
  },
  {
    slug: 'sapphire-ocean',
    title: 'Sapphire Ocean',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Experience thrilling gameplay with Sapphire Ocean.',
    popularityScore: 88,
    minBet: 1.0,
    maxBet: 500,
    rtp: 94.74,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'crystal-pyramid',
    title: 'Crystal Pyramid',
    provider: 'NetEnt',
    type: 'live',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Experience thrilling gameplay with Crystal Pyramid.',
    popularityScore: 99,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.37,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'magic-vikings',
    title: 'Magic Vikings',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'multiplier' }, { tag: 'jackpot' }],
    shortDescription: 'Experience thrilling gameplay with Magic Vikings.',
    popularityScore: 81,
    minBet: 1.0,
    maxBet: 100,
    rtp: 96.0,
    volatility: 'low',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'legendary-empire',
    title: 'Legendary Empire',
    provider: 'Red Tiger',
    type: 'slot',
    tags: [{ tag: 'free-spins' }, { tag: 'adventure' }],
    shortDescription: 'Experience thrilling gameplay with Legendary Empire.',
    popularityScore: 77,
    minBet: 0.2,
    maxBet: 100,
    rtp: 95.82,
    volatility: 'high',
    badges: ['exclusive'],
    status: 'enabled',
  },
  {
    slug: 'super-treasure',
    title: 'Super Treasure',
    provider: 'Red Tiger',
    type: 'live',
    tags: [{ tag: 'jackpot' }, { tag: 'adventure' }],
    shortDescription: 'Experience thrilling gameplay with Super Treasure.',
    popularityScore: 94,
    minBet: 0.5,
    maxBet: 100,
    rtp: 97.55,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'ruby-dragons',
    title: 'Ruby Dragons',
    provider: 'Red Tiger',
    type: 'live',
    tags: [{ tag: 'free-spins' }, { tag: 'bonus' }],
    shortDescription: 'Experience thrilling gameplay with Ruby Dragons.',
    popularityScore: 87,
    minBet: 0.1,
    maxBet: 500,
    rtp: 95.42,
    volatility: 'medium',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'diamond-stars',
    title: 'Diamond Stars',
    provider: 'NetEnt',
    type: 'slot',
    tags: [{ tag: 'multiplier' }, { tag: 'classic' }],
    shortDescription: 'Experience thrilling gameplay with Diamond Stars.',
    popularityScore: 84,
    minBet: 0.5,
    maxBet: 1000,
    rtp: 97.21,
    volatility: 'low',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'diamond-castle',
    title: 'Diamond Castle',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'free-spins' }, { tag: 'bonus' }],
    shortDescription: 'Experience thrilling gameplay with Diamond Castle.',
    popularityScore: 78,
    minBet: 0.5,
    maxBet: 500,
    rtp: 97.12,
    volatility: 'low',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'platinum-dragons',
    title: 'Platinum Dragons',
    provider: 'Red Tiger',
    type: 'live',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Experience thrilling gameplay with Platinum Dragons.',
    popularityScore: 87,
    minBet: 0.5,
    maxBet: 500,
    rtp: 95.03,
    volatility: 'high',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'royal-festival',
    title: 'Royal Festival',
    provider: 'Play\'n GO',
    type: 'table',
    tags: [{ tag: 'classic' }, { tag: 'bonus' }],
    shortDescription: 'Experience thrilling gameplay with Royal Festival.',
    popularityScore: 99,
    minBet: 0.1,
    maxBet: 100,
    rtp: 97.52,
    volatility: 'high',
    badges: [],
    status: 'enabled',
  },

  // ============ NEW GAMES (111 games) ============

  // JACKPOT SLOTS (15 games with jackpotAmount)
  {
    slug: 'mega-jackpot-wheel',
    title: 'Mega Jackpot Wheel',
    provider: 'Aristocrat',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'bonus' }],
    shortDescription: 'Spin the mega wheel for massive progressive jackpots!',
    popularityScore: 98,
    jackpotAmount: 2500000,
    minBet: 0.5,
    maxBet: 500,
    rtp: 94.5,
    volatility: 'high',
    badges: ['jackpot', 'hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'rakin-bacon-gold',
    title: "Rakin' Bacon Gold",
    provider: 'AGS',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'bonus' }],
    shortDescription: 'Chase golden piggies for huge progressive prizes!',
    popularityScore: 95,
    jackpotAmount: 1250000,
    minBet: 0.4,
    maxBet: 400,
    rtp: 95.2,
    volatility: 'high',
    badges: ['jackpot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'blazin-bank-run',
    title: "Blazin' Bank Run",
    provider: 'Aristocrat',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'adventure' }],
    shortDescription: 'Rob the bank for blazing hot jackpot wins!',
    popularityScore: 92,
    jackpotAmount: 750000,
    minBet: 0.3,
    maxBet: 300,
    rtp: 95.8,
    volatility: 'high',
    badges: ['jackpot', 'hot'],
    status: 'enabled',
  },
  {
    slug: 'capital-gains-jackpot',
    title: 'Capital Gains Jackpot',
    provider: 'IGT',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'classic' }],
    shortDescription: 'Invest in spins and watch your capital grow exponentially!',
    popularityScore: 88,
    jackpotAmount: 500000,
    minBet: 0.25,
    maxBet: 250,
    rtp: 96.1,
    volatility: 'medium',
    badges: ['jackpot'],
    status: 'enabled',
  },
  {
    slug: 'cash-machine-deluxe',
    title: 'Cash Machine Deluxe',
    provider: 'Everi',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'classic' }],
    shortDescription: 'Pull the lever on this classic cash machine for deluxe wins!',
    popularityScore: 85,
    jackpotAmount: 350000,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.5,
    volatility: 'medium',
    badges: ['jackpot'],
    status: 'enabled',
  },
  {
    slug: 'double-ruby-fortune',
    title: 'Double Ruby Fortune',
    provider: 'IGT',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'multiplier' }],
    shortDescription: 'Double your fortune with sparkling ruby wilds!',
    popularityScore: 87,
    jackpotAmount: 425000,
    minBet: 0.3,
    maxBet: 300,
    rtp: 95.9,
    volatility: 'high',
    badges: ['jackpot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'smokin-triples-jackpot',
    title: "Smokin' Triples Jackpot",
    provider: 'Everi',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'classic' }],
    shortDescription: 'Triple the heat with smokin hot jackpot combinations!',
    popularityScore: 82,
    jackpotAmount: 180000,
    minBet: 0.1,
    maxBet: 100,
    rtp: 96.2,
    volatility: 'medium',
    badges: ['jackpot'],
    status: 'enabled',
  },
  {
    slug: 'triple-threat-mega',
    title: 'Triple Threat Mega',
    provider: 'AGS',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'multiplier' }],
    shortDescription: 'Face the triple threat of mega multiplier jackpots!',
    popularityScore: 84,
    jackpotAmount: 275000,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.7,
    volatility: 'high',
    badges: ['jackpot', 'hot'],
    status: 'enabled',
  },
  {
    slug: 'wild-wild-7s-jackpot',
    title: 'Wild Wild 7s Jackpot',
    provider: 'IGT',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'classic' }],
    shortDescription: 'Classic 7s go wild with progressive jackpot action!',
    popularityScore: 80,
    jackpotAmount: 150000,
    minBet: 0.1,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'low',
    badges: ['jackpot'],
    status: 'enabled',
  },
  {
    slug: 'spin-cycle-fortune',
    title: 'Spin Cycle Fortune',
    provider: 'Aristocrat',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'bonus' }],
    shortDescription: 'Cycle through spins to unlock fortune wheel jackpots!',
    popularityScore: 86,
    jackpotAmount: 320000,
    minBet: 0.25,
    maxBet: 250,
    rtp: 95.4,
    volatility: 'high',
    badges: ['jackpot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'ultra-diamond-jackpot',
    title: 'Ultra Diamond Jackpot',
    provider: 'IGT',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'multiplier' }],
    shortDescription: 'Ultra rare diamonds trigger ultra massive jackpots!',
    popularityScore: 94,
    jackpotAmount: 890000,
    minBet: 0.5,
    maxBet: 500,
    rtp: 94.8,
    volatility: 'high',
    badges: ['jackpot', 'hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'octo-jackpot',
    title: 'Octo Jackpot',
    provider: 'Everi',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'adventure' }],
    shortDescription: 'Eight arms of fortune reach for eight-figure jackpots!',
    popularityScore: 90,
    jackpotAmount: 620000,
    minBet: 0.3,
    maxBet: 300,
    rtp: 95.3,
    volatility: 'high',
    badges: ['jackpot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'santa-rudolf-jackpot',
    title: 'Santa vs Rudolf Jackpot',
    provider: 'NetEnt',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'bonus' }],
    shortDescription: 'Holiday showdown with festive progressive jackpots!',
    popularityScore: 83,
    jackpotAmount: 445000,
    minBet: 0.2,
    maxBet: 200,
    rtp: 96.3,
    volatility: 'medium',
    badges: ['jackpot', 'new'],
    status: 'enabled',
  },
  {
    slug: 'triple-play-jackpot',
    title: 'Triple Play Jackpot',
    provider: 'AGS',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'classic' }],
    shortDescription: 'Three ways to play, three ways to hit the jackpot!',
    popularityScore: 81,
    jackpotAmount: 380000,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.6,
    volatility: 'medium',
    badges: ['jackpot'],
    status: 'enabled',
  },
  {
    slug: 'hot-teapots-jackpot',
    title: 'Hot Teapots Jackpot',
    provider: 'Aristocrat',
    type: 'slot',
    tags: [{ tag: 'jackpot' }, { tag: 'bonus' }],
    shortDescription: 'Brew up some steaming hot jackpot wins!',
    popularityScore: 79,
    jackpotAmount: 290000,
    minBet: 0.15,
    maxBet: 150,
    rtp: 96.0,
    volatility: 'medium',
    badges: ['jackpot'],
    status: 'enabled',
  },

  // INSTANT WIN / SLINGO GAMES (7 games)
  {
    slug: 'slingo-championship',
    title: 'Slingo Championship',
    provider: 'Gaming Realms',
    type: 'instant',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Compete for championship glory in this ultimate Slingo showdown!',
    popularityScore: 88,
    minBet: 0.5,
    maxBet: 100,
    rtp: 95.0,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'slingo-fire-and-ice',
    title: 'Slingo Fire & Ice',
    provider: 'Gaming Realms',
    type: 'instant',
    tags: [{ tag: 'bonus' }, { tag: 'adventure' }],
    shortDescription: 'Balance fire and ice for elemental Slingo wins!',
    popularityScore: 85,
    minBet: 0.5,
    maxBet: 100,
    rtp: 95.2,
    volatility: 'medium',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'slingo-honey-crew',
    title: 'Slingo Honey Crew',
    provider: 'Gaming Realms',
    type: 'instant',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Join the honey crew for sweet Slingo rewards!',
    popularityScore: 82,
    minBet: 0.5,
    maxBet: 100,
    rtp: 95.5,
    volatility: 'low',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'slingo-journey-asgard',
    title: 'Slingo Journey to Asgard',
    provider: 'Gaming Realms',
    type: 'instant',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Travel to Asgard for mythical Slingo treasures!',
    popularityScore: 86,
    minBet: 0.5,
    maxBet: 100,
    rtp: 95.3,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'slingo-lucky-mcgold',
    title: 'Slingo Lucky McGold',
    provider: 'Gaming Realms',
    type: 'instant',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Find your pot of gold with Lucky McGold!',
    popularityScore: 84,
    minBet: 0.5,
    maxBet: 100,
    rtp: 95.1,
    volatility: 'medium',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'slingo-red-hot',
    title: 'Slingo Red Hot',
    provider: 'Gaming Realms',
    type: 'instant',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Turn up the heat with red hot Slingo action!',
    popularityScore: 87,
    minBet: 0.5,
    maxBet: 100,
    rtp: 95.4,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'slingo-pop',
    title: 'Slingo Pop',
    provider: 'Gaming Realms',
    type: 'instant',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Pop your way to colorful Slingo wins!',
    popularityScore: 80,
    minBet: 0.5,
    maxBet: 100,
    rtp: 95.6,
    volatility: 'low',
    badges: ['new'],
    status: 'enabled',
  },

  // SCIENTIFIC GAMES (4 games)
  {
    slug: 'genies-showtime',
    title: "Genie's Showtime",
    provider: 'Scientific Games',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'adventure' }],
    shortDescription: 'The genie puts on a magical show with spectacular wins!',
    popularityScore: 89,
    minBet: 0.2,
    maxBet: 200,
    rtp: 96.1,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'indiana-wolf',
    title: 'Indiana Wolf',
    provider: 'Scientific Games',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Join Indiana Wolf on an archaeological adventure for riches!',
    popularityScore: 86,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.8,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'safari-rumble',
    title: 'Safari Rumble',
    provider: 'Scientific Games',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Rumble through the safari for wild animal wins!',
    popularityScore: 84,
    minBet: 0.2,
    maxBet: 200,
    rtp: 96.0,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'shivering-strings',
    title: 'Shivering Strings',
    provider: 'Scientific Games',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Spooky strings play haunting melodies of fortune!',
    popularityScore: 81,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.9,
    volatility: 'medium',
    badges: ['new'],
    status: 'enabled',
  },

  // KONAMI GAMES (6 games)
  {
    slug: 'china-shores',
    title: 'China Shores',
    provider: 'Konami',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'Explore the mystical shores of ancient China for treasures!',
    popularityScore: 92,
    minBet: 0.3,
    maxBet: 300,
    rtp: 96.0,
    volatility: 'medium',
    minVipLevel: 'silver',
    badges: ['featured', 'hot'],
    status: 'enabled',
  },
  {
    slug: 'african-diamond',
    title: 'African Diamond',
    provider: 'Konami',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Hunt for precious diamonds in the African wilderness!',
    popularityScore: 88,
    minBet: 0.3,
    maxBet: 300,
    rtp: 95.8,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'dynamite-dash',
    title: 'All Aboard Dynamite Dash',
    provider: 'Konami',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Dash through explosive action on the All Aboard train!',
    popularityScore: 90,
    minBet: 0.4,
    maxBet: 400,
    rtp: 95.5,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'abundant-fortune',
    title: 'Abundant Fortune',
    provider: 'Konami',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Abundance awaits with golden fortune symbols!',
    popularityScore: 85,
    minBet: 0.3,
    maxBet: 300,
    rtp: 96.2,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'fortune-mint',
    title: 'Fortune Mint',
    provider: 'Konami',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Mint your own fortune with lucky coin features!',
    popularityScore: 83,
    minBet: 0.3,
    maxBet: 300,
    rtp: 95.9,
    volatility: 'medium',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'gorilla-riches',
    title: 'Gorilla Riches',
    provider: 'Konami',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'The mighty gorilla guards jungle riches!',
    popularityScore: 87,
    minBet: 0.3,
    maxBet: 300,
    rtp: 96.1,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },

  // EGYPTIAN/MYSTIC THEMED SLOTS (7 games)
  {
    slug: 'sun-of-egypt',
    title: 'Sun of Egypt',
    provider: 'Booongo',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'Bask in the golden rays of Egyptian sun god Ra!',
    popularityScore: 91,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.5,
    volatility: 'high',
    badges: ['featured', 'hot'],
    status: 'enabled',
  },
  {
    slug: 'sun-of-egypt-5',
    title: 'Sun of Egypt 5',
    provider: 'Booongo',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'The fifth chapter of Egyptian sun god adventures!',
    popularityScore: 89,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.7,
    volatility: 'high',
    badges: ['new', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'egypt-fire',
    title: 'Egypt Fire',
    provider: '3 Oaks Gaming',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Fiery pharaohs ignite blazing bonus features!',
    popularityScore: 86,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.8,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'magic-apple',
    title: 'Magic Apple',
    provider: 'Booongo',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Bite into the magic apple for enchanted wins!',
    popularityScore: 82,
    minBet: 0.2,
    maxBet: 200,
    rtp: 96.0,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'magic-clovers',
    title: 'Magic Clovers',
    provider: '3 Oaks Gaming',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Find the four-leaf clover for magical luck!',
    popularityScore: 80,
    minBet: 0.2,
    maxBet: 200,
    rtp: 96.2,
    volatility: 'low',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'maya-lock',
    title: 'Maya Lock',
    provider: 'Belatra',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Unlock ancient Mayan treasures with mystic keys!',
    popularityScore: 84,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.6,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'long-bao-bao',
    title: 'Long Bao Bao',
    provider: 'Booongo',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Dragons bring long-lasting prosperity and wins!',
    popularityScore: 88,
    minBet: 0.2,
    maxBet: 200,
    rtp: 95.9,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },

  // TABLE GAMES (12 games)
  {
    slug: 'american-baccarat',
    title: 'American Baccarat',
    provider: 'Evolution',
    type: 'table',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Classic American-style baccarat with elegant gameplay.',
    popularityScore: 90,
    minBet: 1,
    maxBet: 5000,
    rtp: 98.94,
    volatility: 'low',
    minVipLevel: 'platinum',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'european-roulette',
    title: 'European Roulette',
    provider: 'Evolution',
    type: 'table',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Single zero European roulette with better odds.',
    popularityScore: 93,
    minBet: 0.5,
    maxBet: 2000,
    rtp: 97.3,
    volatility: 'medium',
    minVipLevel: 'gold',
    badges: ['featured', 'hot'],
    status: 'enabled',
  },
  {
    slug: 'blackjack-multi-hand',
    title: 'Blackjack Multi-Hand',
    provider: 'Microgaming',
    type: 'table',
    tags: [{ tag: 'classic' }, { tag: 'multiplier' }],
    shortDescription: 'Play multiple hands simultaneously for more action!',
    popularityScore: 91,
    minBet: 1,
    maxBet: 1000,
    rtp: 99.5,
    volatility: 'low',
    minVipLevel: 'platinum',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'blackjack-classic',
    title: 'Blackjack Classic',
    provider: 'NetEnt',
    type: 'table',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Traditional blackjack with smooth gameplay.',
    popularityScore: 89,
    minBet: 1,
    maxBet: 1000,
    rtp: 99.4,
    volatility: 'low',
    minVipLevel: 'gold',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'blackjack-xchange',
    title: 'Blackjack Xchange',
    provider: 'Slingo',
    type: 'table',
    tags: [{ tag: 'classic' }, { tag: 'bonus' }],
    shortDescription: 'Exchange cards for strategic blackjack advantages!',
    popularityScore: 85,
    minBet: 1,
    maxBet: 500,
    rtp: 99.2,
    volatility: 'low',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'blackjack-3h',
    title: 'Blackjack 3H',
    provider: 'iSoftBet',
    type: 'table',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Three-hand blackjack for triple the excitement!',
    popularityScore: 84,
    minBet: 1,
    maxBet: 500,
    rtp: 99.3,
    volatility: 'low',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'blackjack-double-exposure',
    title: 'Blackjack Double Exposure',
    provider: 'Microgaming',
    type: 'table',
    tags: [{ tag: 'classic' }, { tag: 'bonus' }],
    shortDescription: 'Both dealer cards revealed for strategic play!',
    popularityScore: 86,
    minBet: 1,
    maxBet: 500,
    rtp: 99.3,
    volatility: 'low',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'hard-hit-blackjack',
    title: 'Hard Hit Blackjack',
    provider: 'Pragmatic Play',
    type: 'table',
    tags: [{ tag: 'classic' }, { tag: 'multiplier' }],
    shortDescription: 'Hit hard for aggressive blackjack action!',
    popularityScore: 82,
    minBet: 1,
    maxBet: 500,
    rtp: 99.1,
    volatility: 'medium',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'sic-bo-classic',
    title: 'Sic Bo Classic',
    provider: 'Microgaming',
    type: 'table',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Ancient Chinese dice game with exciting bets.',
    popularityScore: 83,
    minBet: 1,
    maxBet: 1000,
    rtp: 97.2,
    volatility: 'high',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'roulette-classic',
    title: 'Roulette Classic',
    provider: 'NetEnt',
    type: 'table',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Timeless roulette experience with smooth animations.',
    popularityScore: 88,
    minBet: 0.5,
    maxBet: 1000,
    rtp: 97.3,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'blackjack-american',
    title: 'Blackjack American',
    provider: 'Tangente',
    type: 'table',
    tags: [{ tag: 'classic' }],
    shortDescription: 'American-style blackjack with hole card rules.',
    popularityScore: 81,
    minBet: 1,
    maxBet: 500,
    rtp: 99.4,
    volatility: 'low',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'casino-war',
    title: 'Casino War',
    provider: 'Tangente',
    type: 'table',
    tags: [{ tag: 'classic' }, { tag: 'bonus' }],
    shortDescription: 'Simple card battle - highest card wins!',
    popularityScore: 78,
    minBet: 1,
    maxBet: 500,
    rtp: 97.4,
    volatility: 'medium',
    badges: ['new'],
    status: 'enabled',
  },

  // LIVE CASINO GAMES (14 games)
  {
    slug: 'lightning-dice-live',
    title: 'Lightning Dice Live',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Electrifying dice game with lightning multipliers!',
    popularityScore: 94,
    minBet: 0.2,
    maxBet: 1000,
    rtp: 96.2,
    volatility: 'high',
    badges: ['featured', 'hot'],
    status: 'enabled',
  },
  {
    slug: 'super-sic-bo',
    title: 'Super Sic Bo',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Supercharged Sic Bo with random multipliers up to 1000x!',
    popularityScore: 92,
    minBet: 0.2,
    maxBet: 1000,
    rtp: 97.2,
    volatility: 'high',
    badges: ['featured', 'hot'],
    status: 'enabled',
  },
  {
    slug: 'mega-ball-live',
    title: 'Mega Ball Live',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Lottery-style game show with mega multipliers!',
    popularityScore: 96,
    minBet: 0.1,
    maxBet: 500,
    rtp: 95.4,
    volatility: 'high',
    minVipLevel: 'silver',
    badges: ['featured', 'hot', 'exclusive'],
    status: 'enabled',
  },
  {
    slug: 'dream-catcher',
    title: 'Dream Catcher',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Spin the money wheel and catch your dreams!',
    popularityScore: 93,
    minBet: 0.1,
    maxBet: 1000,
    rtp: 96.6,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'fun-an-fun',
    title: 'Fan Tan',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Traditional Asian bead counting game with live dealers.',
    popularityScore: 79,
    minBet: 1,
    maxBet: 2000,
    rtp: 97.6,
    volatility: 'low',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'dragon-tiger',
    title: 'Dragon Tiger',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Fast-paced two-card baccarat variant.',
    popularityScore: 85,
    minBet: 0.5,
    maxBet: 2000,
    rtp: 96.3,
    volatility: 'low',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'rng-blackjack',
    title: 'RNG Blackjack',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Random number generator blackjack with live feel.',
    popularityScore: 82,
    minBet: 1,
    maxBet: 1000,
    rtp: 99.5,
    volatility: 'low',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'rng-craps',
    title: 'RNG Craps',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'classic' }, { tag: 'bonus' }],
    shortDescription: 'Dice game excitement with RNG fairness.',
    popularityScore: 80,
    minBet: 0.5,
    maxBet: 500,
    rtp: 98.6,
    volatility: 'medium',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'rng-mega-ball',
    title: 'RNG Mega Ball',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Mega Ball action available anytime with RNG.',
    popularityScore: 88,
    minBet: 0.1,
    maxBet: 500,
    rtp: 95.4,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'rng-dream-catcher',
    title: 'RNG Dream Catcher',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Dream Catcher excitement with instant play.',
    popularityScore: 84,
    minBet: 0.1,
    maxBet: 1000,
    rtp: 96.6,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'rng-european-roulette',
    title: 'RNG European Roulette',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'classic' }],
    shortDescription: 'European roulette with RNG precision.',
    popularityScore: 86,
    minBet: 0.5,
    maxBet: 2000,
    rtp: 97.3,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'rng-lightning-roulette',
    title: 'RNG Lightning Roulette',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Lightning strikes with multipliers up to 500x!',
    popularityScore: 91,
    minBet: 0.2,
    maxBet: 1000,
    rtp: 97.3,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'instant-roulette',
    title: 'Instant Roulette',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'classic' }],
    shortDescription: 'Multiple wheels for instant roulette action!',
    popularityScore: 87,
    minBet: 0.5,
    maxBet: 1000,
    rtp: 97.3,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'lightning-roulette-table',
    title: 'Lightning Roulette Table',
    provider: 'Evolution',
    type: 'live',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'The original lightning roulette experience!',
    popularityScore: 95,
    minBet: 0.2,
    maxBet: 1000,
    rtp: 97.3,
    volatility: 'high',
    minVipLevel: 'gold',
    badges: ['featured', 'hot', 'exclusive'],
    status: 'enabled',
  },

  // PRAGMATIC PLAY - BIG BASS SERIES (6 games)
  {
    slug: 'big-bass-mission',
    title: 'Big Bass Mission',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'Special ops fishing mission for big bass wins!',
    popularityScore: 93,
    minBet: 0.1,
    maxBet: 250,
    rtp: 96.7,
    volatility: 'high',
    minVipLevel: 'gold',
    badges: ['featured', 'hot'],
    status: 'enabled',
  },
  {
    slug: 'big-bass-brazil',
    title: 'Big Bass Brazil',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'Carnival-themed fishing in Brazilian waters!',
    popularityScore: 90,
    minBet: 0.1,
    maxBet: 250,
    rtp: 96.5,
    volatility: 'high',
    badges: ['new', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'big-bass-doubled',
    title: 'Big Bass Doubled',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'multiplier' }, { tag: 'free-spins' }],
    shortDescription: 'Double the bass, double the fun!',
    popularityScore: 91,
    minBet: 0.1,
    maxBet: 250,
    rtp: 96.6,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'big-bass-lotgl',
    title: 'Big Bass Hold & Spinner',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'free-spins' }],
    shortDescription: 'Hold and spin your way to big bass bonuses!',
    popularityScore: 89,
    minBet: 0.1,
    maxBet: 250,
    rtp: 96.4,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'big-bass-3reeler',
    title: 'Big Bass 3 Reeler',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'classic' }, { tag: 'free-spins' }],
    shortDescription: 'Classic 3-reel big bass action!',
    popularityScore: 85,
    minBet: 0.1,
    maxBet: 100,
    rtp: 96.0,
    volatility: 'medium',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'big-bass-blitz',
    title: 'Big Bass Blitz',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Blitz through bonus rounds for massive catches!',
    popularityScore: 92,
    minBet: 0.1,
    maxBet: 250,
    rtp: 96.7,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },

  // PRAGMATIC PLAY - OTHER SLOTS (30 games)
  {
    slug: 'book-of-light',
    title: 'Book of Light',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'Ancient book illuminates the path to riches!',
    popularityScore: 88,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'dragon-gold-88',
    title: 'Dragon Gold 88',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Lucky 88 dragons bring golden prosperity!',
    popularityScore: 86,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.0,
    volatility: 'medium',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'egypt-classic',
    title: 'Egypt Classic',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'classic' }],
    shortDescription: 'Classic Egyptian adventure with timeless features.',
    popularityScore: 82,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.2,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'fortune-dragon',
    title: 'Fortune Dragon',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'The fortune dragon bestows lucky wins!',
    popularityScore: 87,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.3,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'floating-dragon',
    title: 'Floating Dragon',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'Dragons float across reels bringing multipliers!',
    popularityScore: 89,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.7,
    volatility: 'high',
    minVipLevel: 'gold',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'fonzo-fortune',
    title: 'Fonzo Fortune',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Fonzo the fox hunts for fortune features!',
    popularityScore: 80,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.1,
    volatility: 'medium',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'giza-gods',
    title: 'Giza Gods',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Egyptian gods guard ancient Giza treasures!',
    popularityScore: 85,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.4,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'john-montana',
    title: 'John Montana',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'Wild west adventure with cowboy John Montana!',
    popularityScore: 83,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.2,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'mayan-gods',
    title: 'Mayan Gods',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Ancient Mayan deities offer divine rewards!',
    popularityScore: 84,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.3,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'fortune-noodles',
    title: 'Fortune Noodles',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Slurp up lucky noodles for fortune bonuses!',
    popularityScore: 81,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.0,
    volatility: 'medium',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'tutankhamun',
    title: 'Tutankhamun',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'Explore King Tuts tomb for legendary treasures!',
    popularityScore: 86,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'bigger-splash',
    title: 'Bigger Splash',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Make a bigger splash for bigger prizes!',
    popularityScore: 79,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.1,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'diamond-strike',
    title: 'Diamond Strike',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'classic' }, { tag: 'jackpot' }],
    shortDescription: 'Strike it rich with dazzling diamond wins!',
    popularityScore: 87,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'medium',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'fight-multiplier',
    title: 'Fight Night',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Fight for knockout multiplier wins!',
    popularityScore: 82,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.2,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'fortune-tree',
    title: 'Fortune Tree',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'The fortune tree blooms with golden rewards!',
    popularityScore: 84,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.3,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'bermuda-riches',
    title: 'Bermuda Riches',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Dive into Bermuda Triangle mysteries for riches!',
    popularityScore: 85,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.4,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'big-dawgs',
    title: 'Big Dawgs',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Top dogs fetch top prizes in this howling hit!',
    popularityScore: 88,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.6,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'chicken-chase',
    title: 'Chicken Chase',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'classic' }],
    shortDescription: 'Chase golden eggs in this feathered frenzy!',
    popularityScore: 80,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.0,
    volatility: 'medium',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'dh-cluster',
    title: 'Dragon Hero',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Heroic dragons cluster for epic wins!',
    popularityScore: 83,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.2,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'forge-of-olympus',
    title: 'Forge of Olympus',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Gods forge mighty multipliers on Mount Olympus!',
    popularityScore: 90,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'starlight-princess',
    title: 'Starlight Princess',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Princess of stars grants cosmic multipliers!',
    popularityScore: 95,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    minVipLevel: 'gold',
    badges: ['featured', 'hot', 'exclusive'],
    status: 'enabled',
  },
  {
    slug: 'sugar-rush-x',
    title: 'Sugar Rush X',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'multiplier' }, { tag: 'bonus' }],
    shortDescription: 'Sweet candies cascade for sugar-coated wins!',
    popularityScore: 93,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'big-badge',
    title: 'Big Badge',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Sheriff badges unlock wild west bonuses!',
    popularityScore: 81,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.1,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'joker-king',
    title: 'Joker King',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'classic' }, { tag: 'bonus' }],
    shortDescription: 'The Joker King rules the reels with wild power!',
    popularityScore: 84,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.3,
    volatility: 'medium',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'mustang-gold',
    title: 'Mustang Gold',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'jackpot' }],
    shortDescription: 'Wild mustangs gallop toward golden jackpots!',
    popularityScore: 89,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'scarab-queen',
    title: 'Scarab Queen',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'The Scarab Queen protects Egyptian treasures!',
    popularityScore: 85,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.4,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'mystery-4096',
    title: 'Mystery 4096 Ways',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: '4096 ways to uncover mysterious wins!',
    popularityScore: 86,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'cleos-eye',
    title: "Cleo's Eye",
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Cleopatras mystical eye reveals hidden treasures!',
    popularityScore: 84,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.3,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'juicy-fruits',
    title: 'Juicy Fruits',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'classic' }, { tag: 'multiplier' }],
    shortDescription: 'Squeeze juicy wins from fruity combinations!',
    popularityScore: 82,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.0,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'lions-1024',
    title: 'Lions 1024',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: '1024 ways to roar with lion pride wins!',
    popularityScore: 87,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },

  // PRAGMATIC PLAY - WAYS SLOTS (9 games)
  {
    slug: '5-lions-2',
    title: '5 Lions Megaways',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Five lucky lions bring megaways fortune!',
    popularityScore: 90,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['featured', 'hot'],
    status: 'enabled',
  },
  {
    slug: 'aztec-ways',
    title: 'Aztec Bonanza',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Aztec riches cascade in bonanza style!',
    popularityScore: 88,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'eternity-ways',
    title: 'Gates of Eternity',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Eternal gates open to infinite multipliers!',
    popularityScore: 86,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.4,
    volatility: 'high',
    badges: ['new'],
    status: 'enabled',
  },
  {
    slug: 'expanding-ways',
    title: 'Expanding Wilds',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'bonus' }, { tag: 'multiplier' }],
    shortDescription: 'Wilds expand across reels for mega wins!',
    popularityScore: 84,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.3,
    volatility: 'high',
    badges: ['hot'],
    status: 'enabled',
  },
  {
    slug: 'japan-ways',
    title: 'Rising Sun Megaways',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'free-spins' }],
    shortDescription: 'Japanese rising sun illuminates megaways wins!',
    popularityScore: 85,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
  {
    slug: 'kraken-ways',
    title: 'Release the Kraken',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Unleash the Kraken for monstrous multipliers!',
    popularityScore: 89,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.5,
    volatility: 'high',
    badges: ['hot', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'mighty-freya',
    title: 'Mighty Freya',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'bonus' }],
    shortDescription: 'Norse goddess Freya grants mighty victories!',
    popularityScore: 83,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.2,
    volatility: 'high',
    badges: ['new', 'featured'],
    status: 'enabled',
  },
  {
    slug: 'modern-fruits',
    title: 'Modern Fruits',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'classic' }, { tag: 'bonus' }],
    shortDescription: 'Classic fruits with a modern megaways twist!',
    popularityScore: 80,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.0,
    volatility: 'medium',
    badges: [],
    status: 'enabled',
  },
  {
    slug: 'pearls-ways',
    title: 'Ocean Pearls',
    provider: 'Pragmatic Play',
    type: 'slot',
    tags: [{ tag: 'adventure' }, { tag: 'multiplier' }],
    shortDescription: 'Dive deep for precious ocean pearl wins!',
    popularityScore: 82,
    minBet: 0.2,
    maxBet: 100,
    rtp: 96.1,
    volatility: 'high',
    badges: ['featured'],
    status: 'enabled',
  },
]

export async function seedGames(payload: Payload, reset = false): Promise<void> {
  console.log('Seeding games...')

  // Delete all existing games if reset is true
  if (reset) {
    console.log('Resetting games collection...')
    const allGames = await payload.find({
      collection: 'games',
      limit: 1000,
    })

    for (const game of allGames.docs) {
      await payload.delete({
        collection: 'games',
        id: game.id,
      })
    }
    console.log(`Deleted ${allGames.docs.length} existing games`)
  }

  for (const gameData of gamesData) {
    try {
      // Check if game already exists (skip check if reset is true)
      if (!reset) {
        const existing = await payload.find({
          collection: 'games',
          where: {
            slug: { equals: gameData.slug },
          },
        })

        if (existing.docs.length > 0) {
          console.log(`Game "${gameData.title}" already exists, skipping...`)
          continue
        }
      }

      // Get thumbnail from uploaded media
      const thumbnailId = getGameMediaId(gameData.slug)

      // Create game
      const createData: Record<string, unknown> = {
        ...gameData,
      }

      if (thumbnailId) {
        createData.thumbnail = thumbnailId
      }

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await payload.create({
        collection: 'games',
        data: createData as any,
      })

      console.log(`Created game: ${gameData.title}${thumbnailId ? ' (with image)' : ''}`)
    } catch (error) {
      console.error(`Failed to create game "${gameData.title}":`, error)
    }
  }

  console.log('Games seeding completed!')
}

export { gamesData, gameImageMap }
